name: Deploy Flutter Web

on:
  push:
    branches:
      - main # Change strictly to 'master' if your main branch is called master

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd flutter_portfolio
          flutter pub get

      - name: Build Web
        run: |
          cd flutter_portfolio
          flutter build web --release --base-href="/EstebanRDZ/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flutter_portfolio/build/web